version: '3.8'

services:
  dev_cpu:
    build: 
      dockerfile: ./DockerfileCpu
    container_name: goat_shape_estimation_cpu
    volumes:
      - ./:/workspace
    command: tail -f /dev/null
  dev_gpu:
    build:
      dockerfile: ./DockerfileGpu
    container_name: goat_shape_estimation_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./:/workspace
    command: tail -f /dev/null